apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum-go
spec:
  replicas: 2
  selector:
    matchLabels:
      project: forum
      app: forum-go
  template:
    metadata:
      labels:
        project: forum
        app: forum-go
    spec:
      imagePullSecrets: 
      - name: "docker-regsitry-auth"
      containers:
      - image: registry.cn-shenzhen.aliyuncs.com/lin_cx/forum-go:v1.0.0
        name: forum-go
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
          name: forum-go-1
          protocol: TCP