apiVersion: v1
kind: Service
metadata:
  labels:
    app: forum-go
  name: forum-go
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8082
    nodePort: 30082
  selector:
    app: forum-go
  type: NodePort