apiVersion: v1
kind: Service
metadata:
  labels:
    app: alpine-forum-java
  name: alpine-forum-java
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
    nodePort: 30081
  selector:
    app: alpine-forum-java
  type: NodePort