apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum-vue
spec:
  replicas: 2
  selector:
    matchLabels:
      project: forum
      app: forum-vue
  template:
    metadata:
      labels:
        project: forum
        app: forum-vue
    spec:
      imagePullSecrets: 
      - name: "docker-regsitry-auth"
      containers:
      - image: registry.cn-shenzhen.aliyuncs.com/lin_cx/forum-vue:v1.0.0
        name: forum-vue
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: forum-vue-1
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 20