apiVersion: v1
kind: Service
metadata:
  labels:
    app: forum-vue
  name: forum-vue
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    app: forum-vue
  type: NodePort