apiVersion: v1
kind: Service
metadata:
  labels:
    app: forum-py
  name: forum-py
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8083
    nodePort: 30083
  selector:
    app: forum-py
  type: NodePort